// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultilink } from "../storyblok.d.ts";
export interface Feature {
  name?: string;
  component: "feature";
  _uid: string;
  [k: string]: unknown;
}

export interface Grid {
  columns?: (Feature | Grid | Menu | Page | Teaser)[];
  component: "grid";
  _uid: string;
  [k: string]: unknown;
}

export interface Menu {
  name?: string;
  link?: Exclude<StoryblokMultilink, { linktype?: "email" } | { linktype?: "asset" }>;
  component: "menu";
  _uid: string;
  [k: string]: unknown;
}

export interface Page {
  body?: (Feature | Grid | Menu | Page | Teaser)[];
  component: "page";
  _uid: string;
  [k: string]: unknown;
}

export interface Teaser {
  headline?: string;
  component: "teaser";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = Page;
